### ISSUE TITLE
Master Zoning Law

### ISSUE THREAD

**Issue by HenriquePi** [Charter-City-Toronto/the-charter#7]
ReverRace:
all construction will be low density. 
50% of any give area must be greenspace
Yeul:
only small trees though, no shadows allowed.

**Comment by yeul** [comment]
only small trees though, no shadows allowed.

**Comment by sashimii** [comment]
![image](https://user-images.githubusercontent.com/5431418/151288966-317ae8bf-c7b2-4da5-a169-458511c6d9d9.png)
